// content/photography.ts
// Replace `image` paths with real photography under /public/images.
// Orientation drives the gallery rhythm.

import type { PhotoItem } from "@/lib/types";

export const photography: PhotoItem[] = [
  {
    id: "ph-01",
    title: "Cold light, outer fjord",
    location: "Vestland, Norway",
    year: "2025",
    category: "NATURE",
    caption:
      "Field note from the living north. A reminder that the living world is not a backdrop, but the system we belong to.",
    image: "/images/photo-01.svg",
    orientation: "landscape",
  },
  {
    id: "ph-02",
    title: "Surfacing",
    location: "Norwegian Sea",
    year: "2025",
    category: "WILDLIFE",
    caption: "A breath taken at the boundary between two worlds.",
    image: "/images/photo-02.svg",
    orientation: "portrait",
  },
  {
    id: "ph-03",
    title: "The old forest holds its water",
    location: "Trøndelag, Norway",
    year: "2024",
    category: "NATURE",
    caption: "Soil that has been left alone long enough to remember how to keep the rain.",
    image: "/images/photo-03.svg",
    orientation: "square",
  },
  {
    id: "ph-04",
    title: "Hands that know the season",
    location: "Lofoten, Norway",
    year: "2024",
    category: "PEOPLE",
    caption: "People who live close to a system tend to understand its limits without being told.",
    image: "/images/photo-04.svg",
    orientation: "portrait",
  },
  {
    id: "ph-05",
    title: "Edge of the ice",
    location: "Svalbard",
    year: "2025",
    category: "EXPEDITIONS",
    caption: "A boundary that is moving, and a record of where it stood.",
    image: "/images/photo-05.svg",
    orientation: "landscape",
  },
  {
    id: "ph-06",
    title: "Tidal arithmetic",
    location: "Oslofjord, Norway",
    year: "2025",
    category: "PLACES",
    caption: "A fjord keeps an honest ledger; it shows you exactly what it is given.",
    image: "/images/photo-06.svg",
    orientation: "square",
  },
  {
    id: "ph-07",
    title: "Understory",
    location: "Amazonia",
    year: "2024",
    category: "NATURE",
    caption: "Most of the living world happens below the canopy, out of frame.",
    image: "/images/photo-07.svg",
    orientation: "portrait",
  },
  {
    id: "ph-08",
    title: "Notebook, second day",
    location: "Field",
    year: "2025",
    category: "FIELD NOTES",
    caption: "A page is also a kind of photograph.",
    image: "/images/photo-08.svg",
    orientation: "landscape",
  },
  {
    id: "ph-09",
    title: "Colony",
    location: "Runde, Norway",
    year: "2024",
    category: "WILDLIFE",
    caption: "Ten thousand individual decisions, holding the shape of one system.",
    image: "/images/photo-09.svg",
    orientation: "landscape",
  },
  {
    id: "ph-10",
    title: "City as habitat",
    location: "Oslo, Norway",
    year: "2025",
    category: "PLACES",
    caption: "How humans organise life on land — also an ecology, also a system.",
    image: "/images/photo-10.svg",
    orientation: "portrait",
  },
  {
    id: "ph-11",
    title: "Low sun on the kelp",
    location: "Norwegian coast",
    year: "2025",
    category: "WILDLIFE",
    caption: "The forests we forget about because they grow underwater.",
    image: "/images/photo-11.svg",
    orientation: "square",
  },
  {
    id: "ph-12",
    title: "Watcher",
    location: "Northern Norway",
    year: "2024",
    category: "PEOPLE",
    caption: "Attention is the first form of care.",
    image: "/images/photo-12.svg",
    orientation: "portrait",
  },
];
